PROG = prog
CC = g++
CPPFLAGS = -g -Wall -std=c++11
OBJS = main.o ListCollection.o

$(PROG) : $(OBJS)
	$(CC) -o $(PROG) $(OBJS)

main.o : main.cpp
	$(CC) $(CPPFLAGS) -c main.cpp

ListCollection.o : ListCollection.h ListCollection.cpp
	$(CC) $(CPPFLAGS) -c ListCollection.cpp

clean:
	rm -f core $(PROG) $(OBJS)

rebuild:
	make clean
	make